id: I1239A9CD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:11:28+00:00'
last_modified: '2022-06-08T11:25:04.175328+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20266
  title: རྒྱའི་ཡིག་ཚང་དུ་འཁོད་པའི་བོད་དང་འབྲེལ་བའི་ལོ་རྒྱུས། དེབ། ༡-༤
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C744:
      image_group_id: I8LS20800
      title: ''
      total_pages: 393
      order: 1
      base_file: C744.txt
    D80B:
      image_group_id: I8LS20801
      title: ''
      total_pages: 447
      order: 2
      base_file: D80B.txt
    4F42:
      image_group_id: I8LS20802
      title: ''
      total_pages: 369
      order: 3
      base_file: 4F42.txt
    '4508':
      image_group_id: I8LS20803
      title: ''
      total_pages: 353
      order: 4
      base_file: 4508.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
