id: P009492
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:41:14.078177
source_metadata:
  id: bdr:W8LS20266
  title: རྒྱའི་ཡིག་ཚང་དུ་འཁོད་པའི་བོད་དང་འབྲེལ་བའི་ལོ་རྒྱུས། དེབ། ༡-༤
  author: ''
  volumes:
    517a05a43e384b10be7a702636451db0:
      image_group_id: I8LS20800
      title: ''
      volume_number: 1
      total_pages: 393
      base_file: v001.txt
    8855024e5f9042dd91665de7450888ac:
      image_group_id: I8LS20801
      title: ''
      volume_number: 2
      total_pages: 447
      base_file: v002.txt
    ae1160279a8b4c1dbde09b85b8f77a97:
      image_group_id: I8LS20802
      title: ''
      volume_number: 3
      total_pages: 369
      base_file: v003.txt
    e0e5aad996d747e581da9ffde1e5b99e:
      image_group_id: I8LS20803
      title: ''
      volume_number: 4
      total_pages: 353
      base_file: v004.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
